### ISSUE TITLE
Filter option of fee doesn't work

### ISSUE THREAD

**Issue by ghost** [unibe-ese/ese2015-team9#48]

**Comment by brnsnt** [comment]
Wenn de nid? Das het bi mir vori funktioniert.

**Comment by curtys** [comment]
zb min:21 max:25 de zeigts aues a

**Comment by brnsnt** [comment]
hane idee was da chönnt passiere... lueges när a

**Comment by Laeri** [comment]
I gloube es funktioniert immer no nid. Weme min fee uf 0 het zeigts die mit 0 nümme ah, u weme dr maxfee ufetueht zeigts o kener me ah
