### ISSUE TITLE
Offers can not be removed immediatly after creation

### ISSUE THREAD

**Issue by curtys** [unibe-ese/ese2015-team9#50]
After creating an offer, the user is redirected to the account page. If he tries to remove any offer an 404 error is shown.

**Comment by brnsnt** [comment]
Hani gester gfixed. Het nach /auth/account/message/... gsuecht ka.
De message param wird iz vo showProfile() diräkt gsetzt, d links sötte o aui up to date si.

**Comment by curtys** [comment]
Jup, funktioniert itz.
